## Academic performance analysis (using NumPy library tools)

### 1

The source array contains the scores of the English language course student entrance exam. The students are divided into 15 groups, 10 people each:

In [1]:
import numpy as np

scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

In [2]:
zero_pupils = scores == 0
print(f'The score "0" was got by {zero_pupils.sum()} students.')

The score "0" was got by 13 students.


In [3]:
fifty_pupils = scores > 50
print(f'The score more than 50 was got by {fifty_pupils.sum()} students.')

The score more than 50 was got by 64 students.


In [4]:
ffty_svty_pupils = (scores >= 50) & (scores <= 70)
print(f'{ffty_svty_pupils.sum()} people got the score not lower than 50, but not higher than 70.')

26 people got the score not lower than 50, but not higher than 70.


In [21]:
print(f'There is the highest average score for the entrance exam in group number {np.array([i.mean() for i in scores]).argmax()}.')

There is the highest average score for the entrance exam in group number 9.


In [6]:
nonzero = scores[scores > 0]
print(f'The \"nonzero\" array with the scores above 0:\n{nonzero}')

The "nonzero" array with the scores above 0:
[ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]


In [7]:
min_score = nonzero.min()
print(f'The minimum exam score in all the groups: {min_score}.')

The minimum exam score in all the groups: 1.


In [8]:
advanced = nonzero[nonzero > 80]
print(f'The \"advanced\" array that includes student scores above 80:\n{advanced}.')

The "advanced" array that includes student scores above 80:
[ 98 100  82 100 100  95  83 100  94  90  87  89  99  88  94 100  81  98
  88 100  86  96 100  98  87 100  88  89].


In [9]:
print(f'\"Advanced\" array dimension: {advanced.ndim}.')

"Advanced" array dimension: 1.


In [10]:
print(f'\"Advanced\" array shape: {advanced.shape}.')

"Advanced" array shape: (28,).


In [11]:
print(f'The total number of elements in the array \"advanced\" array: {advanced.size}.')

The total number of elements in the array "advanced" array: 28.


In [12]:
sto = scores == 100
print(f'The boolean array \"sto\", where True corresponds to exam scores equal to 100, and False corresponds to all other scores:\n{sto}')

The boolean array "sto", where True corresponds to exam scores equal to 100, and False corresponds to all other scores:
[[False False False False False False False False False False]
 [False False False  True False False False False  True False]
 [False False False False  True False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False

In [13]:
print(f'The scores of the listeners of the first seven groups:\n{scores[:7]}')

The scores of the listeners of the first seven groups:
[[ 20  40  56  80   0   5  25  27  74   1]
 [  0  98  67 100   8  56  34  82 100   7]
 [ 78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77]
 [ 90  87  41  89  52   0   5  17  28  99]
 [ 32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100]]


### 2

The sourse score array `A`:

In [14]:
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6],
             [3, 1, 0, 2],
             [6, 5, 6, 8],
             [1, 0, 0, 4]])

In [15]:
A_height = A.shape[0]
A_width = A.shape[1]
A_tr = np.zeros((A_width, A_height))
for i in range(A_height):
    for j in range(A_width):
        A_tr[j][i] = A[i][j]
print(f'Array A transposed without using NumPy built-in methods:\n{A_tr}')

Array A transposed without using NumPy built-in methods:
[[2. 8. 3. 6. 1.]
 [9. 7. 1. 5. 0.]
 [8. 5. 0. 6. 0.]
 [0. 6. 2. 8. 4.]]


In [16]:
print(f'Is the transposed array similar to the same calculated using the function \".T\"? {np.array_equal(A.T, A_tr)}')

Is the transposed array similar to the same calculated using the function ".T"? True


### 3

Student N works as a math tutor and manages classes of various types:
* preliminary class for the Unified State Exam,
* preliminary for Olympiads,
* elementary school students class that "pulls up" mathematics.

The `classes` array stores the number of lessons taught in five working days, and the `prices` array stores the cost of one lesson (it is assumed that a tutor conducts classes of the same type for all day, with the same cost).

In [17]:
classes = np.array([3, 3, 2, 0, 2])
prices = np.array([1500, 1500, 2500, 1000, 1000])

In [18]:
np.dot(prices, classes)
print(f"Tutor's weekly income: {np.dot(prices, classes)}")

Tutor's weekly income: 16000


### 4

There are two Boolean arrays expert1 and expert2. They are based on the results of students' essay scores data working set by two different experts. In these arrays the value True means a grade of "satisfactory" and higher, and the value False – unsatisfactory. In total there were 15 essays evaluated, 5 essays for each of the three topics:

In [19]:
expert1 = np.array([[True, False, False, True, True],
                   [False, True, False, False, True],
                   [True, True, True, False, False]])
expert2 = np.array([[True, False, False, False, True],
                   [False, False, False, False, False],
                   [True, False, True, False, False]])

Only students who have received satisfactory grades from both experts will get a positive assesment.

In [20]:
expert = expert1 & expert2
print(f'In total only {expert.sum()} students will get a positive assesment')

In total only 4 students will get a positive assesment
