## Ice cream sales and other data processing (using NumPy library tools)

### 1

Downloading an array from the `array_hw.ncpu` file, which contains the sales volumes of ice cream (in pieces) in 5 stores for one week in June (7 days, from Monday to Sunday):

In [1]:
import numpy as np

In [2]:
arr = np.load("array_hw.npy")
print(f'Array \'arr\':\n{arr}')

Array 'arr':
[[100  80  70  60 120]
 [ 65  55  20  50  60]
 [ 80  90  75  80  60]
 [ 45  60  70  20  40]
 [ 82  47  56  89  92]
 [115 120 113 106 107]
 [ 46  74  23  34  19]]


In the table, stores are arranged in columns (1 store = 1 column, 5 in total), and days are arranged in rows (1 day = 1 row, 7 in total), this is difficult for an intuitive perception of its contents.

In [3]:
print(f'The original form of the table: {arr.shape}')

The original form of the table: (7, 5)


In [4]:
arr = arr.transpose()
print(f'The shape of the table after transposition: {arr.shape}')

The shape of the table after transposition: (5, 7)


Later, the sales information was updated. It turned out that on Sunday the fifth store sold not 19 portions of ice cream, but 25. And on Tuesday the second store sold not 55 portions, but 65.
Let's enter this data into the array:

In [5]:
arr[4][6] = 25
arr[1][1] = 65
print(f'The table after data updating:\n{arr}')

The table after data updating:
[[100  65  80  45  82 115  46]
 [ 80  65  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  25]]


In [6]:
print(f'Total sales of ice cream in all stores: {np.sum(arr)}')

Total sales of ice cream in all stores: 2439


### 2

The `income` array contains ungrouped store profit values in thousands at the beginning, middle and end of the year, for four successive years.

In [7]:
income = np.array([1000, 2000, 3500,
                   2500, 1500, 3800,
                   1200, 9000, 12000,
                   4500, 6700, 11000])
print(f'The original array:\n{income}')

The original array:
[ 1000  2000  3500  2500  1500  3800  1200  9000 12000  4500  6700 11000]


In [8]:
income = income.reshape(4, 3)
print(f'The same array with values grouped by year and season:\n{income}')

The same array with values grouped by year and season:
[[ 1000  2000  3500]
 [ 2500  1500  3800]
 [ 1200  9000 12000]
 [ 4500  6700 11000]]


### 3

The `turnout` list contains the values of the turnout at the polling stations as a percentage:

In [9]:
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
print(f'Original list: {turnout}')
turnout_r = np.array([round(i, 1) for i in turnout])
print(f'An array of values rounded with Python (not NumPy): {turnout_r}')

Original list: [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
An array of values rounded with Python (not NumPy): [23.6 45.8 34.9 57.3 56.5 67.2]


In [10]:
turnout = np.array(turnout)
turnout_r = turnout.round(1)
print(f'An array of values rounded with NumPy: {turnout_r}')

An array of values rounded with NumPy: [23.6 45.8 34.9 57.3 56.6 67.2]


### 4

A structured array `happy` containing 3 indicators of the **2012 International Happiness Index** related to 3 countries.

In [11]:
happy = np.array([('Israel', 55.2, 7.4, 81.6), ('State of Palestine', 51.2, 4.8, 72.8), ('United Kingdom', 49.7, 7, 80.2)],
              dtype=[('country','U20'), ('HPI', float), ('life satisfaction', float), ('life expectancy', float)])
print(f'The structured array \'happy\':\n{happy}')

The structured array 'happy':
[('Israel', 55.2, 7.4, 81.6) ('State of Palestine', 51.2, 4.8, 72.8)
 ('United Kingdom', 49.7, 7. , 80.2)]


In [12]:
happy_list = happy.tolist()
happy_list[1]
print(f'The \'happy\' array converted to a ordinary list:\n{happy_list}')
print(f'The second item in the list: {happy_list[1]}')

The 'happy' array converted to a ordinary list:
[('Israel', 55.2, 7.4, 81.6), ('State of Palestine', 51.2, 4.8, 72.8), ('United Kingdom', 49.7, 7.0, 80.2)]
The second item in the list: ('State of Palestine', 51.2, 4.8, 72.8)


### 5

Creating the `build_array()` function using Python (without using `np.eye()`), which takes as input the dimension of a square matrix (a two-dimensional array in which the number of rows and the number of columns match) and creates a unit matrix `E` (array) of the appropriate dimension.

In [13]:
def build_array(dim):
    list_i = list()
    for i in range(dim):
        list_j = list()
        for j in range(dim):
            if i == j:
                list_j.append(1)
            else:
                list_j.append(0)
        list_i.append(list_j)
    return np.array(list_i)

n = 4
build_array(n)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Creating the function `my_reshape()`, which takes an array and its new dimension (a pair of numbers) as input, then:
* if the specified measurements are correct, it returns an array of the new dimension;
* if they are incorrect, it returns an empty array (example: a new 4×3 array cannot be made from a 2×5 array, because there are 10 elements in the old array, and 12 in the new one).

In [14]:
def my_reshape(array, rows, cols):
        if len(array.ravel()) == rows * cols:
            return array.reshape(rows, cols)
        else:
            return np.array([])

A = np.array([[2, 4, 6],
            [4, 8, 10]])

my_reshape(A, 6, 1)

array([[ 2],
       [ 4],
       [ 6],
       [ 4],
       [ 8],
       [10]])

In [15]:
my_reshape(A, 4, 2)

array([], dtype=float64)